system: 
  echarts:
    api: http://10.206.16.13:3000
  admin: http://10.206.16.13:8082
    
server:
  port: 8083
  
spring:
  application:
    name: electric-Api
  
  datasource:
    url: jdbc:mysql://10.206.16.13:3306/dat?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: DAT@TestMysql147

  redis:
    host: 10.206.16.13
    port: 6379
    password: DAT@TestRedis147

#token配置
token: 

wx:
  mp:
    configs:
      - appId: wxb5930c3148e86017
        secret: 6cb08aec1c895b67a66fb174fba96d8f