system: 
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /Users/fronttang/api-workspace/electric/electric-api

server:
  port: 8083
  
spring:
  application:
    name: electric-Api
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dianantong?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password

  redis:
    host: localhost
    port: 6379

#token配置
token: 