system: 
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /Users/fronttang/develop/dat

server:
  port: 8083
  
spring:
  application:
    name: electric-Api
  
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/dianantong?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    #username: root
    #password: password
    url: jdbc:mysql://129.211.210.175:3306/dat?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: DAT@TestMysql147

  redis:
    #host: localhost
    #port: 6379
    host: 129.211.210.175
    port: 6379
    password: DAT@TestRedis147

#token配置
token: 

logging:
  file: 
    path: ./logs